-- PAWGLOW Manufacturing Suite Database Schema
-- Migration for Material Categories, Materials, Formulas, and Products Management

-- Create material_type enum
create type "public"."material_type" as enum ('raw_material', 'packaging', 'label');

-- Create unit_type enum
create type "public"."unit_type" as enum ('kg', 'g', 'l', 'ml', 'units', 'meters', 'cm');

-- Material Categories Table
create table "public"."material_categories" (
    "id" uuid generated by default as uuid primary key,
    "name" text not null,
    "prefix" text not null unique,
    "description" text,
    "tenant_id" text not null default requesting_user_id(),
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone default timezone('utc'::text, now())
);

-- Materials Table  
create table "public"."materials" (
    "id" uuid generated by default as uuid primary key,
    "category_id" uuid not null references "public"."material_categories"("id") on delete restrict,
    "name" text not null,
    "code" text not null unique,
    "description" text,
    "cost_per_unit" numeric(10,4) not null check (cost_per_unit >= 0),
    "unit_type" unit_type not null,
    "material_type" material_type not null,
    "supplier" text,
    "min_stock_level" numeric(10,4) default 0 check (min_stock_level >= 0),
    "current_stock" numeric(10,4) default 0 check (current_stock >= 0),
    "tenant_id" text not null default requesting_user_id(),
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone default timezone('utc'::text, now())
);

-- Formulas Table
create table "public"."formulas" (
    "id" uuid generated by default as uuid primary key,
    "name" text not null,
    "description" text,
    "created_by" text not null,
    "tenant_id" text not null default requesting_user_id(),
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone default timezone('utc'::text, now())
);

-- Formula Versions Table
create table "public"."formula_versions" (
    "id" uuid generated by default as uuid primary key,
    "formula_id" uuid not null references "public"."formulas"("id") on delete cascade,
    "version_number" integer not null,
    "is_active" boolean default false,
    "notes" text,
    "created_by" text not null,
    "tenant_id" text not null default requesting_user_id(),
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    unique(formula_id, version_number)
);

-- Formula Ingredients Table
create table "public"."formula_ingredients" (
    "id" uuid generated by default as uuid primary key,
    "formula_version_id" uuid not null references "public"."formula_versions"("id") on delete cascade,
    "material_id" uuid not null references "public"."materials"("id") on delete restrict,
    "percentage" numeric(5,2) not null check (percentage > 0 and percentage <= 100),
    "tenant_id" text not null default requesting_user_id(),
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    unique(formula_version_id, material_id)
);

-- Manufacturing Products Table (named to avoid conflict with Stripe products)
create table "public"."manufacturing_products" (
    "id" uuid generated by default as uuid primary key,
    "name" text not null,
    "description" text,
    "sku" text unique,
    "formula_version_id" uuid references "public"."formula_versions"("id") on delete set null,
    "packaging_material_id" uuid references "public"."materials"("id") on delete set null,
    "label_material_id" uuid references "public"."materials"("id") on delete set null,
    "net_weight" numeric(10,4) not null check (net_weight > 0),
    "net_weight_unit" unit_type not null default 'g',
    "cogs" numeric(10,4) check (cogs >= 0),
    "selling_price" numeric(10,4) check (selling_price >= 0),
    "status" text default 'draft' check (status in ('draft', 'active', 'discontinued')),
    "tenant_id" text not null default requesting_user_id(),
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    "updated_at" timestamp with time zone default timezone('utc'::text, now())
);

-- Create indexes for performance optimization
create index "idx_material_categories_tenant" on "public"."material_categories"("tenant_id");
create index "idx_material_categories_prefix" on "public"."material_categories"("prefix");
create index "idx_materials_tenant" on "public"."materials"("tenant_id");
create index "idx_materials_category" on "public"."materials"("category_id");
create index "idx_materials_code" on "public"."materials"("code");
create index "idx_materials_type" on "public"."materials"("material_type");
create index "idx_formulas_tenant" on "public"."formulas"("tenant_id");
create index "idx_formula_versions_formula" on "public"."formula_versions"("formula_id");
create index "idx_formula_versions_active" on "public"."formula_versions"("is_active");
create index "idx_formula_ingredients_version" on "public"."formula_ingredients"("formula_version_id");
create index "idx_formula_ingredients_material" on "public"."formula_ingredients"("material_id");
create index "idx_manufacturing_products_tenant" on "public"."manufacturing_products"("tenant_id");
create index "idx_manufacturing_products_formula" on "public"."manufacturing_products"("formula_version_id");
create index "idx_manufacturing_products_packaging" on "public"."manufacturing_products"("packaging_material_id");
create index "idx_manufacturing_products_label" on "public"."manufacturing_products"("label_material_id");
create index "idx_manufacturing_products_sku" on "public"."manufacturing_products"("sku");

-- Enable Row Level Security
alter table "public"."material_categories" enable row level security;
alter table "public"."materials" enable row level security;
alter table "public"."formulas" enable row level security;
alter table "public"."formula_versions" enable row level security;
alter table "public"."formula_ingredients" enable row level security;
alter table "public"."manufacturing_products" enable row level security;

-- RLS Policies for Material Categories
create policy "Users can view own material categories" on "public"."material_categories"
    for select using (tenant_id = requesting_user_id());

create policy "Users can insert own material categories" on "public"."material_categories"
    for insert with check (tenant_id = requesting_user_id());

create policy "Users can update own material categories" on "public"."material_categories"
    for update using (tenant_id = requesting_user_id());

create policy "Users can delete own material categories" on "public"."material_categories"
    for delete using (tenant_id = requesting_user_id());

-- RLS Policies for Materials
create policy "Users can view own materials" on "public"."materials"
    for select using (tenant_id = requesting_user_id());

create policy "Users can insert own materials" on "public"."materials"
    for insert with check (tenant_id = requesting_user_id());

create policy "Users can update own materials" on "public"."materials"
    for update using (tenant_id = requesting_user_id());

create policy "Users can delete own materials" on "public"."materials"
    for delete using (tenant_id = requesting_user_id());

-- RLS Policies for Formulas
create policy "Users can view own formulas" on "public"."formulas"
    for select using (tenant_id = requesting_user_id());

create policy "Users can insert own formulas" on "public"."formulas"
    for insert with check (tenant_id = requesting_user_id());

create policy "Users can update own formulas" on "public"."formulas"
    for update using (tenant_id = requesting_user_id());

create policy "Users can delete own formulas" on "public"."formulas"
    for delete using (tenant_id = requesting_user_id());

-- RLS Policies for Formula Versions
create policy "Users can view own formula versions" on "public"."formula_versions"
    for select using (tenant_id = requesting_user_id());

create policy "Users can insert own formula versions" on "public"."formula_versions"
    for insert with check (tenant_id = requesting_user_id());

create policy "Users can update own formula versions" on "public"."formula_versions"
    for update using (tenant_id = requesting_user_id());

create policy "Users can delete own formula versions" on "public"."formula_versions"
    for delete using (tenant_id = requesting_user_id());

-- RLS Policies for Formula Ingredients
create policy "Users can view own formula ingredients" on "public"."formula_ingredients"
    for select using (tenant_id = requesting_user_id());

create policy "Users can insert own formula ingredients" on "public"."formula_ingredients"
    for insert with check (tenant_id = requesting_user_id());

create policy "Users can update own formula ingredients" on "public"."formula_ingredients"
    for update using (tenant_id = requesting_user_id());

create policy "Users can delete own formula ingredients" on "public"."formula_ingredients"
    for delete using (tenant_id = requesting_user_id());

-- RLS Policies for Manufacturing Products
create policy "Users can view own manufacturing products" on "public"."manufacturing_products"
    for select using (tenant_id = requesting_user_id());

create policy "Users can insert own manufacturing products" on "public"."manufacturing_products"
    for insert with check (tenant_id = requesting_user_id());

create policy "Users can update own manufacturing products" on "public"."manufacturing_products"
    for update using (tenant_id = requesting_user_id());

create policy "Users can delete own manufacturing products" on "public"."manufacturing_products"
    for delete using (tenant_id = requesting_user_id());

-- Function to generate next material code
CREATE OR REPLACE FUNCTION generate_material_code(p_category_prefix text)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_next_number integer;
    v_code text;
BEGIN
    -- Get the next number for this category prefix
    SELECT COALESCE(MAX(CAST(SUBSTRING(code, LENGTH(p_category_prefix) + 1) AS integer)), 0) + 1
    INTO v_next_number
    FROM materials
    WHERE code LIKE p_category_prefix || '%'
    AND tenant_id = requesting_user_id();
    
    -- Generate the new code
    v_code := p_category_prefix || LPAD(v_next_number::text, 3, '0');
    
    RETURN v_code;
END;
$$;

-- Function to validate formula ingredient percentages
CREATE OR REPLACE FUNCTION validate_formula_percentages(p_formula_version_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_total_percentage numeric;
BEGIN
    SELECT COALESCE(SUM(percentage), 0)
    INTO v_total_percentage
    FROM formula_ingredients
    WHERE formula_version_id = p_formula_version_id;
    
    RETURN v_total_percentage = 100;
END;
$$;

-- Function to calculate COGS for a manufacturing product
CREATE OR REPLACE FUNCTION calculate_product_cogs(p_product_id uuid)
RETURNS numeric(10,4)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_product RECORD;
    v_total_cost numeric(10,4) := 0;
    v_ingredient_cost numeric(10,4);
BEGIN
    -- Get product details
    SELECT * INTO v_product
    FROM manufacturing_products
    WHERE id = p_product_id
    AND tenant_id = requesting_user_id();
    
    IF NOT FOUND THEN
        RETURN NULL;
    END IF;
    
    -- Calculate ingredient costs if formula is set
    IF v_product.formula_version_id IS NOT NULL THEN
        SELECT SUM(fi.percentage / 100 * 
                  (m.cost_per_unit * 
                   CASE 
                       WHEN v_product.net_weight_unit = 'g' AND m.unit_type = 'kg' THEN v_product.net_weight / 1000
                       WHEN v_product.net_weight_unit = 'kg' AND m.unit_type = 'g' THEN v_product.net_weight * 1000
                       WHEN v_product.net_weight_unit = 'ml' AND m.unit_type = 'l' THEN v_product.net_weight / 1000
                       WHEN v_product.net_weight_unit = 'l' AND m.unit_type = 'ml' THEN v_product.net_weight * 1000
                       ELSE v_product.net_weight
                   END))
        INTO v_ingredient_cost
        FROM formula_ingredients fi
        JOIN materials m ON fi.material_id = m.id
        WHERE fi.formula_version_id = v_product.formula_version_id;
        
        v_total_cost := COALESCE(v_ingredient_cost, 0);
    END IF;
    
    -- Add packaging cost
    IF v_product.packaging_material_id IS NOT NULL THEN
        SELECT cost_per_unit
        INTO v_ingredient_cost
        FROM materials
        WHERE id = v_product.packaging_material_id
        AND tenant_id = requesting_user_id();
        
        v_total_cost := v_total_cost + COALESCE(v_ingredient_cost, 0);
    END IF;
    
    -- Add label cost
    IF v_product.label_material_id IS NOT NULL THEN
        SELECT cost_per_unit
        INTO v_ingredient_cost
        FROM materials
        WHERE id = v_product.label_material_id
        AND tenant_id = requesting_user_id();
        
        v_total_cost := v_total_cost + COALESCE(v_ingredient_cost, 0);
    END IF;
    
    RETURN v_total_cost;
END;
$$;

-- Trigger to automatically update updated_at columns
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$;

-- Create triggers for updated_at
CREATE TRIGGER update_material_categories_updated_at
    BEFORE UPDATE ON material_categories
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_materials_updated_at
    BEFORE UPDATE ON materials
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_formulas_updated_at
    BEFORE UPDATE ON formulas
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_manufacturing_products_updated_at
    BEFORE UPDATE ON manufacturing_products
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Grant permissions to authenticated users
GRANT ALL ON material_categories TO authenticated;
GRANT ALL ON materials TO authenticated;
GRANT ALL ON formulas TO authenticated;
GRANT ALL ON formula_versions TO authenticated;
GRANT ALL ON formula_ingredients TO authenticated;
GRANT ALL ON manufacturing_products TO authenticated;

-- Grant usage permissions for the functions
GRANT EXECUTE ON FUNCTION generate_material_code(text) TO authenticated;
GRANT EXECUTE ON FUNCTION validate_formula_percentages(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION calculate_product_cogs(uuid) TO authenticated;